services:
  _defaults:
    autowire: true
    autoconfigure: true
  Pixel\TownHallBundle\Controller\Website\:
    resource: '../../Controller/Website'

  Pixel\TownHallBundle\Twig\SettingsExtension:
    public: true
    autowire: true
    tags:
      - {name: twig.extension}